apiVersion: v1
kind: Secret
metadata:
  name: oke-admin-service-account-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: oke-admin
type: kubernetes.io/service-account-token
